#!/bin/bash
curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1635721200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data1.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1639321200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data2.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1642921200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data3.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1646521200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data4.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1650117600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data5.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1653717600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data6.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1657317600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data7.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1660917600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data8.json


curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1664517600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data9.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1668121200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_10.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1671721200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_11.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1675321200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_12.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1678921200000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_13.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1682517600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_14.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1686117600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_15.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1689717600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_16.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1693317600000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_17.json

curl -X GET "https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&startTime=1696917600000&endTime=1698793199000&limit=1000" | jq . > /home/jsaye/Projet/Data_brute/1h_granul/data_18.json

jq -s 'add' /home/jsaye/Projet/Data_brute/1h_granul/*.json > /home/jsaye/Projet/Data_brute/1h_granul.json



