version: '3.3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_pwd'
      MYSQL_DATABASE: 'opa_db'
      MYSQL_USER: 'opa_user'
      MYSQL_PASSWORD: 'opa_pwd'
    networks:
      - mysql-compose-network
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes :
      # - ./requirements/volumes/data:/volumes/data
      - ./requirements/mysql/volumes/db:/var/lib/mysql
      - ./requirements/mysql/volumes/script:/volumes/script
networks:
    mysql-compose-network:

