version: "3.3"

services:
  database:
    container_name: my_mongo3
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$login
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=$password
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - ./sample_training:/data/db

  mongoexpress:
    container_name: mongo-express3
    image: mongo-express:0.54
    depends_on:
      - database
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=my_mongo3
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$login
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=$login
      - ME_CONFIG_BASICAUTH_PASSWORD=$password
    ports:
      - '8081:8081'
    volumes: 
      - ./sample_training:/data/db      

networks:
  mongo-compose-network:
    
